// UI contract — テスト (Testing Library / Playwright) が依存してよい data-ui 安定名の名簿。
//
// 規約 (foundation ui/contract.ts):
//   - 第一選択はロール/アクセシブルネーム。data-ui は文言変更で壊れない補助名。
//   - 値は `領域.対象[.動作]`。リテラルを散らさず必ずこの名簿経由で参照する。
//   - settings / pickers の名前は後続エージェントがこの名簿に追記する。

export const UI = {
  nav: {
    home: 'nav.home',
    menu: 'nav.menu',
    user: 'nav.user',
    ws: 'nav.ws',
    menuMemo: 'nav.menu.memo',
    menuShared: 'nav.menu.shared',
    menuSettings: 'nav.menu.settings',
  },
  home: {
    start: 'home.start',
    grid: 'home.grid',
    addPatient: 'home.addPatient',
    patientQr: 'home.patientQr',
  },
  patient: {
    card: 'patient.card',
    statusOption: 'patient.status.option',
    move: 'patient.move',
    editPopup: 'patient.edit.popup',
    name: 'patient.edit.name',
    room: 'patient.edit.room',
    formatSet: 'patient.edit.formatSet',
  },
  detail: {
    prev: 'detail.prev',
    next: 'detail.next',
    meta: 'detail.meta',
    metaBottom: 'detail.meta.bottom',
    actionBar: 'detail.actionBar',
    qrShow: 'detail.qr.show',
    qrDialog: 'detail.qr.dialog',
  },
  problem: {
    card: 'problem.card',
    list: 'problem.list',
    row: 'problem.row',
    input: 'problem.input',
    add: 'problem.add',
    delete: 'problem.delete',
  },
  format: {
    cell: 'format.cell',
    cellInput: 'format.cell.input',
    normalBtn: 'format.normal',
    chip: 'format.chip',
    launcher: 'format.launcher',
    sheet: 'format.sheet',
    sheetApply: 'format.sheet.apply',
    sheetCancel: 'format.sheet.cancel',
    sheetClear: 'format.sheet.clear',
  },
  qr: {
    show: 'qr.show',
    card: 'qr.card',
    dialog: 'qr.dialog',
    canvas: 'qr.canvas',
    pageMeta: 'qr.pageMeta',
    prev: 'qr.prev',
    next: 'qr.next',
    scan: 'qr.scan',
    recvStatus: 'qr.recv.status',
  },
  recv: {
    open: 'recv.open',
    box: 'recv.box',
    area: 'recv.area',
    clear: 'recv.clear',
  },
  list: {
    editToggle: 'list.editToggle',
    row: 'list.row',
    rowBody: 'list.rowBody',
  },
  move: {
    dialog: 'move.dialog',
    rowPrefix: 'move.row',
    newWs: 'move.newWs',
  },
  exit: {
    confirm: 'exit.confirm',
  },
  settings: {
    view: 'settings.view',
    clearTarget: 'settings.clearTarget',
    tagList: 'settings.tags.list',
    tagAdd: 'settings.tags.add',
    tagRow: 'settings.tags.row',
    tagDelete: 'settings.tags.delete',
    formatList: 'settings.formats.list',
    formatAdd: 'settings.formats.add',
    formatRow: 'settings.formats.row',
    formatEdit: 'settings.formats.edit',
    formatDelete: 'settings.formats.delete',
    formatEditDialog: 'settings.formats.editDialog',
    formatEditName: 'settings.formats.editName',
    formatEditSave: 'settings.formats.editSave',
    formatEditAddItem: 'settings.formats.editAddItem',
    formatEditQrShare: 'settings.formats.editQrShare',
    groupList: 'settings.groups.list',
    groupAdd: 'settings.groups.add',
    groupRow: 'settings.groups.row',
    groupEdit: 'settings.groups.edit',
    groupDelete: 'settings.groups.delete',
    groupEditDialog: 'settings.groups.editDialog',
    groupEditName: 'settings.groups.editName',
    groupEditSave: 'settings.groups.editSave',
    groupEditQrShare: 'settings.groups.editQrShare',
    qrShow: 'settings.qr.show',
    qrReceiveOpen: 'settings.qr.receiveOpen',
    qrReceiveDialog: 'settings.qr.receiveDialog',
    qrReceiveScan: 'settings.qr.receiveScan',
    ioImport: 'settings.io.import',
    ioExport: 'settings.io.export',
    ioDeviceImport: 'settings.io.deviceImport',
    ioDeviceExport: 'settings.io.deviceExport',
    ioFile: 'settings.io.file',
    logExport: 'settings.log.export',
    logClear: 'settings.log.clear',
    restoreList: 'settings.restore.list',
    restoreRow: 'settings.restore.row',
    restoreAction: 'settings.restore.action',
    restoreDelete: 'settings.restore.delete',
    userList: 'settings.users.list',
    userRow: 'settings.users.row',
    userDelete: 'settings.users.delete',
    wardList: 'settings.wards.list',
    wardRow: 'settings.wards.row',
    wardRename: 'settings.wards.rename',
    wardDelete: 'settings.wards.delete',
    wardAdd: 'settings.wards.add',
  },
  picker: {
    userDialog: 'picker.user.dialog',
    userRow: 'picker.user.row',
    userAdd: 'picker.user.add',
    userRename: 'picker.user.rename',
    wsDialog: 'picker.ws.dialog',
    wsRow: 'picker.ws.row',
    wsAdd: 'picker.ws.add',
    wsRename: 'picker.ws.rename',
    wsDelete: 'picker.ws.delete',
  },
  lifecycle: {
    delete: 'lifecycle.delete',
    permanentDelete: 'lifecycle.permanentDelete',
    restore: 'lifecycle.restore',
    restoreDialog: 'lifecycle.restoreDialog',
  },
  tags: {
    filterOpen: 'tags.filter.open',
    filterSheet: 'tags.filter.sheet',
    filterOption: 'tags.filter.option',
    selectChip: 'tags.select.chip',
    addBtn: 'tags.add',
  },
} as const;
