/*
 * UI contract: テストが依存してよい安定名（data-ui 属性値）。
 *
 * - これらの名前は日本語文言の変更で壊れない契約。Playwright/Testing Library から参照する。
 * - DOM 構造や CSS class には依存させない。
 * - 詳細とポリシーは docs/dev/ui-contract.md。
 */
export const UI = {
  // 期間（データ抽出条件）。ヘッダー中央の「現在コンテキスト表示」+ 軽量ピッカー。ホーム/財務諸表/仕訳で共有
  period: {
    // ヘッダーの現在コンテキスト表示（タップで対応ピッカーを開く）
    yearTrigger: 'period.year.trigger',
    monthTrigger: 'period.month.trigger',
    // 軽量ピッカー本体
    yearPicker: 'period.year.picker',
    monthPicker: 'period.month.picker',
    // ピッカーの行（選択で即反映して閉じる）
    yearRow: 'period.year.row',
    monthRow: 'period.month.row',
    allRow: 'period.all.row',
    fullYearRow: 'period.fullYear.row',
    // トレンド（SVG グラフ）
    trend: 'period.trend',
    trendChart: 'period.trend.chart',
    trendPoint: 'period.trend.point',
  },
  dashboard: {
    view: 'dashboard.view',
    // 日常入力 3 種（ホーム下部の固定バー＝主導線）
    entryBar: 'dashboard.entryBar',
    income: 'dashboard.entry.income',
    expense: 'dashboard.entry.expense',
    transfer: 'dashboard.entry.transfer',
    // 収支/財政状態の項目別ボタン（タップで各項目の「内訳 + 推移」ページへ）。
    statRevenue: 'dashboard.stat.revenue',
    statExpense: 'dashboard.stat.expense',
    statNetIncome: 'dashboard.stat.netIncome',
    statAssets: 'dashboard.stat.assets',
    statLiabilities: 'dashboard.stat.liabilities',
    statNetAssets: 'dashboard.stat.netAssets',
    // 当月の仕訳プレビュー
    journalPreview: 'dashboard.journal.preview',
    journalOpenAll: 'dashboard.journal.openAll',
  },
  // 収入の内訳
  incomeBreakdown: {
    view: 'incomeBreakdown.view',
    row: 'incomeBreakdown.row',
    total: 'incomeBreakdown.total',
  },
  // 支出の内訳
  expenseBreakdown: {
    view: 'expenseBreakdown.view',
    categoryList: 'expenseBreakdown.categoryList',
    categoryRow: 'expenseBreakdown.categoryRow',
    normalExpense: 'expenseBreakdown.normalExpense',
    monthlyCost: 'expenseBreakdown.monthlyCost',
    total: 'expenseBreakdown.total',
  },
  // 収支
  netIncome: {
    view: 'netIncome.view',
    revenue: 'netIncome.revenue',
    expense: 'netIncome.expense',
    result: 'netIncome.result',
  },
  // 資産の内訳
  assetsBreakdown: {
    view: 'assetsBreakdown.view',
    row: 'assetsBreakdown.row',
    total: 'assetsBreakdown.total',
    reserveSub: 'assetsBreakdown.reserveSub',
  },
  // 負債の内訳
  liabilitiesBreakdown: {
    view: 'liabilitiesBreakdown.view',
    row: 'liabilitiesBreakdown.row',
    total: 'liabilitiesBreakdown.total',
    cashflowLink: 'liabilitiesBreakdown.cashflowLink',
  },
  // 純資産
  netAssets: {
    view: 'netAssets.view',
    row: 'netAssets.row',
    total: 'netAssets.total',
  },
  journal: {
    view: 'journal.view',
    list: 'journal.entry.list',
    monthlyRecognition: 'journal.monthlyRecognition',
    monthlyRecognitionRow: 'journal.monthlyRecognition.row',
    search: 'journal.search',
    clearAccountFilter: 'journal.filter.clearAccount',
    showFuture: 'journal.filter.showFuture',
    filterTag: 'journal.filter.tag',
    entry: {
      save: 'journal.entry.save',
      cancel: 'journal.entry.cancel',
      delete: 'journal.entry.delete',
      reverse: 'journal.entry.reverse',
      detailToggle: 'journal.entry.detailToggle',
      manualSwitch: 'journal.entry.manualSwitch',
      tags: 'journal.entry.tags',
      debitTags: 'journal.entry.debitTags',
      creditTags: 'journal.entry.creditTags',
      allocateToggle: 'journal.entry.allocateToggle',
      allocateMonths: 'journal.entry.allocateMonths',
      monthlyizeContinue: 'journal.entry.monthlyizeContinue',
      monthlyizeRepayToggle: 'journal.entry.monthlyizeRepayToggle',
      monthlyizeRepayAccount: 'journal.entry.monthlyizeRepayAccount',
      monthlyizeRepayCount: 'journal.entry.monthlyizeRepayCount',
      monthlyizeRepayStart: 'journal.entry.monthlyizeRepayStart',
      loanRepayToggle: 'journal.entry.loanRepayToggle',
      loanRepayAccount: 'journal.entry.loanRepayAccount',
      loanRepayCount: 'journal.entry.loanRepayCount',
      loanRepayStart: 'journal.entry.loanRepayStart',
      ccToggle: 'journal.entry.ccToggle',
      ccName: 'journal.entry.ccName',
      ccCategory: 'journal.entry.ccCategory',
      fixedMonthlyToggle: 'journal.entry.fixedMonthlyToggle',
      fixedMonthlyCategory: 'journal.entry.fixedMonthlyCategory',
      reserveCreate: 'journal.entry.reserveCreate',
      reserveName: 'journal.entry.reserveName',
      loanArrange: 'journal.entry.loanArrange',
      liabilityCreate: 'journal.entry.liabilityCreate',
      liabilityCreateName: 'journal.entry.liabilityCreate.name',
      liabilityCreateRole: 'journal.entry.liabilityCreate.role',
      liabilityCreateSave: 'journal.entry.liabilityCreate.save',
      date: 'journal.entry.date',
      description: 'journal.entry.description',
      item: 'journal.entry.item',
      flow: 'journal.entry.flow',
      flowSource: 'journal.entry.flow.source',
      flowDestination: 'journal.entry.flow.destination',
      flowError: 'journal.entry.flow.error',
      debitAccount: 'journal.entry.debitAccount',
      creditAccount: 'journal.entry.creditAccount',
      amount: 'journal.entry.amount',
      memo: 'journal.entry.memo',
    },
  },
  accounts: {
    view: 'accounts.view',
    create: 'accounts.create',
    save: 'accounts.save',
    list: 'accounts.list',
    type: 'accounts.type',
    role: 'accounts.role',
    adjust: 'accounts.adjust',
  },
  allocations: {
    view: 'allocations.view',
    list: 'allocations.list',
    showCompleted: 'allocations.showCompleted',
    edit: 'allocations.edit',
    editDialog: 'allocations.editDialog',
    editName: 'allocations.edit.name',
    editKind: 'allocations.edit.kind',
    editAmount: 'allocations.edit.amount',
    editCostMonths: 'allocations.edit.costMonths',
    editRepeat: 'allocations.edit.repeat',
    editStartMonth: 'allocations.edit.startMonth',
    editEndMonth: 'allocations.edit.endMonth',
    editExpense: 'allocations.edit.expense',
    editStatus: 'allocations.edit.status',
    editSave: 'allocations.edit.save',
    editImpactWarning: 'allocations.edit.impactWarning',
    dispose: 'allocations.dispose',
    disposeDialog: 'allocations.disposeDialog',
    disposeDate: 'allocations.dispose.date',
    disposeProceeds: 'allocations.dispose.proceeds',
    disposeDestination: 'allocations.dispose.destination',
    disposeConfirm: 'allocations.dispose.confirm',
  },
  tags: {
    view: 'tags.view',
    create: 'tags.create',
    save: 'tags.save',
    name: 'tags.name',
    list: 'tags.list',
    period: 'tags.period',
    entrySummary: 'tags.summary.entry',
    lineSummary: 'tags.summary.line',
  },
  wallets: {
    view: 'wallets.view',
    scopeList: 'wallets.scope.list',
    scopeCreate: 'wallets.scope.create',
    scopeName: 'wallets.scope.name',
    scopeSave: 'wallets.scope.save',
    instrumentList: 'wallets.instrument.list',
    instrumentCreate: 'wallets.instrument.create',
    instrumentName: 'wallets.instrument.name',
    instrumentAccount: 'wallets.instrument.account',
    instrumentKind: 'wallets.instrument.kind',
    instrumentSave: 'wallets.instrument.save',
  },
  adjustments: {
    view: 'adjustments.view',
    account: 'adjust.account',
    date: 'adjust.date',
    kind: 'adjust.kind',
    actual: 'adjust.actual',
    save: 'adjust.save',
    createDialog: 'adjustments.createDialog',
    list: 'adjustments.list',
    row: 'adjustments.row',
    rowEdit: 'adjustments.row.edit',
    rowDelete: 'adjustments.row.delete',
    editDialog: 'adjustments.editDialog',
    editAccount: 'adjustments.edit.account',
    editDate: 'adjustments.edit.date',
    editKind: 'adjustments.edit.kind',
    editActual: 'adjustments.edit.actual',
    editSave: 'adjustments.edit.save',
    deleteConfirm: 'adjustments.deleteConfirm',
    openingMode: 'opening.mode',
    openingAccount: 'opening.account',
    openingName: 'opening.name',
    openingRole: 'opening.role',
    openingAmount: 'opening.amount',
    openingDate: 'opening.date',
    openingSave: 'opening.save',
    openingList: 'opening.list',
    openingRow: 'opening.row',
    openingRowEdit: 'opening.row.edit',
    openingRowDelete: 'opening.row.delete',
    openingEditDialog: 'opening.editDialog',
    openingEditAmount: 'opening.edit.amount',
    openingEditDate: 'opening.edit.date',
    openingEditSave: 'opening.edit.save',
    openingDeleteConfirm: 'opening.deleteConfirm',
  },
  cashflow: {
    view: 'cashflow.view',
    until: 'cashflow.until',
    addSchedule: 'cashflow.schedule.create',
    list: 'cashflow.schedule.list',
    scheduleSave: 'cashflow.schedule.save',
    schedulePost: 'cashflow.schedule.post',
    scheduleName: 'cashflow.schedule.name',
    scheduleAmount: 'cashflow.schedule.amount',
    scheduleAccount: 'cashflow.schedule.account',
    scheduleCounter: 'cashflow.schedule.counter',
    scheduleFlowSource: 'cashflow.schedule.flow.source',
    scheduleFlowDestination: 'cashflow.schedule.flow.destination',
    scheduleInstallments: 'cashflow.schedule.installments',
    liabilityList: 'cashflow.liability.list',
    freeTrend: 'cashflow.freeTrend',
    futureList: 'cashflow.future.list',
    advancedToggle: 'cashflow.advanced.toggle',
    scheduleEntryTags: 'cashflow.schedule.entryTags',
    scheduleAccountTags: 'cashflow.schedule.accountTags',
    scheduleCounterTags: 'cashflow.schedule.counterTags',
    summary: 'cashflow.summary',
    addReserve: 'cashflow.reserve.create',
    reserveList: 'cashflow.reserve.list',
    reserveSave: 'cashflow.reserve.save',
    reserveName: 'cashflow.reserve.name',
  },
  settings: {
    view: 'settings.view',
    manageList: 'settings.manage.list',
    exportJson: 'settings.exportJson',
    importJson: 'settings.importJson',
    importFile: 'settings.importFile',
    resetAll: 'settings.resetAll',
  },
  nav: {
    home: 'nav.home',
    menuButton: 'nav.menu.button',
    menu: 'nav.menu',
  },
  dialog: {
    confirm: 'dialog.confirm',
    cancel: 'dialog.cancel',
  },
  toast: 'toast',
} as const;
